LOAD 'build/release/quackformers.duckdb_extension';
CREATE TEMP TABLE QUESTIONS(random_questions) AS
VALUES
    ('What is the capital of France?'),
    ('How does a car engine work?'),
    ('What is the tallest mountain in the world?'),
    ('How do airplanes stay in the air?'),
    ('What is the speed of light?'),
    ('Who wrote "To Kill a Mockingbird"?'),
    ('What is the chemical formula for water?'),
    ('How do I bake a chocolate cake?'),
    ('What is the population of Japan?'),
    ('How does photosynthesis work?'),
    ('What is the currency of Brazil?'),
    ('Who painted the Mona Lisa?'),
    ('What is the boiling point of water?'),
    ('How do I play the guitar?'),
    ('What is the largest ocean on Earth?'),
    ('Who discovered gravity?'),
    ('What is the process of making glass?'),
    ('How do I learn a new language?'),
    ('What is the history of the internet?'),
    ('How does a computer processor work?'),
    ('What is the capital of Germany?'),
    ('How does a rocket launch into space?'),
    ('What is the smallest country in the world?'),
    ('How do plants grow?'),
    ('What is the formula for calculating area?'),
    ('Who invented the telephone?'),
    ('What is the freezing point of water?'),
    ('How do I make a cup of coffee?'),
    ('What is the population of India?'),
    ('How does the human brain work?'),
    ('What is the currency of Canada?'),
    ('Who painted "Starry Night"?'),
    ('What is the melting point of gold?'),
    ('How do I play the piano?'),
    ('What is the longest river in the world?'),
    ('Who discovered electricity?'),
    ('What is the process of making paper?'),
    ('How do I improve my memory?'),
    ('What is the history of photography?'),
    ('How does a solar panel work?'),
    ('What is the capital of Italy?'),
    ('How does a microwave oven work?'),
    ('What is the largest desert on Earth?'),
    ('How do birds fly?'),
    ('What is the formula for calculating volume?'),
    ('Who invented the light bulb?'),
    ('What is the boiling point of mercury?'),
    ('How do I make a sandwich?'),
    ('What is the population of the United States?'),
    ('How does the circulatory system work?'),
    ('What is the currency of Australia?'),
    ('Who painted "The Last Supper"?'),
    ('What is the melting point of silver?'),
    ('How do I play chess?'),
    ('What is the deepest ocean trench?'),
    ('Who discovered penicillin?'),
    ('What is the process of making steel?'),
    ('How do I learn to code?'),
    ('What is the history of aviation?'),
    ('How does a wind turbine generate electricity?'),
    ('What is the capital of Spain?'),
    ('How does a refrigerator work?'),
    ('What is the largest island in the world?'),
    ('How do fish breathe underwater?'),
    ('What is the formula for calculating speed?'),
    ('Who invented the airplane?'),
    ('What is the freezing point of alcohol?'),
    ('How do I make a smoothie?'),
    ('What is the population of Brazil?'),
    ('How does the digestive system work?'),
    ('What is the currency of Japan?'),
    ('Who painted "The Scream"?'),
    ('What is the melting point of iron?'),
    ('How do I play basketball?'),
    ('What is the tallest waterfall in the world?'),
    ('Who discovered radioactivity?'),
    ('What is the process of making ceramics?'),
    ('How do I learn to swim?'),
    ('What is the history of computers?'),
    ('How does a camera capture images?'),
    ('What is the capital of Russia?'),
    ('How does a television work?'),
    ('What is the largest lake in the world?'),
    ('How do mammals reproduce?'),
    ('What is the formula for calculating force?'),
    ('Who invented the printing press?'),
    ('What is the boiling point of ethanol?'),
    ('How do I make a salad?'),
    ('What is the population of China?'),
    ('How does the immune system work?'),
    ('What is the currency of the United Kingdom?'),
    ('Who painted "Guernica"?'),
    ('What is the melting point of copper?'),
    ('How do I play soccer?'),
    ('What is the longest mountain range in the world?'),
    ('Who discovered the structure of DNA?'),
    ('What is the process of making plastic?'),
    ('How do I learn to draw?'),
    ('What is the history of space exploration?'),
    ('How does a battery store energy?')
;

SELECT len(embedrock(random_questions)) from questions limit 10;

SELECT bedrockchat('whats the capital of Australia?');

-- PRAGMA enable_profiling;

-- -- SELECT embed_jina('THIS IS A SENTENCE') embedded_questions;
-- -- SELECT embed_jina('THIS IS ANOTHER SENTENCE') embedded_questions;
-- SELECT embedrock('this is a test sentence') embedded_question;
